export const DATABASE_ID = process.env.APPWRITE_DATABASE_ID!;

export const STORAGE = {
  PROFILE_IMAGES: process.env.APPWRITE_PROFILE_IMAGES_BUCKET_ID!,
} as const;

export const COLLECTIONS = {
  USERS: process.env.APPWRITE_USERS_COLLECTION_ID!,
  ALUMNI: process.env.APPWRITE_COLLECTION_ID!,
  EMPLOYMENT: process.env.APPWRITE_EMPLOYMENT_COLLECTION_ID!,
  EDUCATION: process.env.APPWRITE_EDUCATION_COLLECTION_ID!,
  SURVEYS: process.env.APPWRITE_SURVEY_COLLECTION_ID!,
  ANNOUNCEMENTS: process.env.APPWRITE_ANNOUNCEMENT_COLLECTION_ID!,
} as const;
